// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdvettquvvqkhimbjsjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdmV0dHF1dnZxa2hpbWJqc2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzcxMzMsImV4cCI6MjA2MjkxMzEzM30.dVFBFG3kxwHGtkixiYqzZrMntL_wkr_P8HL1m2NblQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);